In [1]:
print("Hello")

Hello

In [3]:
import numpy as np

In [3]:
my_list = [2, 3, 4]
my_list

[2, 3, 4]

In [4]:
array_from_list = np.array(my_list)
array_from_list

array([2, 3, 4])

In [6]:
linspace_array = np.linspace(0, 10, 11)  # Creates 11 numbers from 0 to 1
linspace_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0]      # Gets the first row
first_row

array([2, 3, 4])

In [14]:
second_row = arr[1]      # Gets the second row
second_row

array([4, 5, 6])

In [9]:
first_col = arr[:, 0]  # Gets the first column
first_col

array([2, 4])

In [11]:
third_col = arr[:, 2]  # Gets the third column
third_col

array([4, 6])

In [10]:
second_col = arr[:, 1]  # Gets the second column
second_col

array([3, 5])

In [15]:
import pandas as pd

In [16]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [17]:
df = pd.DataFrame(data, columns=columns)

df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [21]:
df[['MSRP','Make']]

    MSRP     Make
0   2000   Nissan
1  27150  Hyundai
2  54990    Lotus
3  34450      GMC
4  32340   Nissan

In [22]:
df['id'] = [1, 2, 3, 4, 5]

df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [23]:
del df['id']

df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [24]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [27]:
df.loc[4]

Make                   Nissan
Model                Frontier
Year                     2017
Engine HP               261.0
Engine Cylinders            6
Transmission Type      MANUAL
Vehicle_Style          Pickup
MSRP                    32340
Name: 4, dtype: object

In [28]:
df.iloc[[0, 2, 4]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [29]:
df['Engine Cylinders'] + 1

0    5
1    5
2    5
3    5
4    7
Name: Engine Cylinders, dtype: int64

In [39]:
df['Make'].str.lower()

0     nissan
1    hyundai
2      lotus
3        gmc
4     nissan
Name: Make, dtype: str

In [41]:
df['Vehicle_Style'].str.replace(' ', '_').str.lower()

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: str

In [43]:
df.MSRP.mean()

np.float64(30186.0)

In [44]:
df['MSRP'].max()

np.int64(54990)

In [45]:
df['MSRP'].min()

np.int64(2000)

In [49]:
df['MSRP'].describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [51]:
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [55]:
df.Make.nunique()

4

In [56]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        5
MSRP                 5
dtype: int64

In [57]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [58]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [59]:
df.isnull()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False

In [62]:
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

In [65]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [66]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'MSRP': 32340}]

In [69]:
u = np.array([2, 4, 6, 8])

2 * u

array([ 4,  8, 12, 16])

In [86]:
v = np.array([1, 0, 0, 2])

u + v

array([ 3,  4,  6, 10])

In [71]:
u * v

array([ 2,  0,  0, 16])

In [73]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [74]:
vector_vector_multiplication(u, v)

np.float64(18.0)

In [75]:
u.dot(v)

np.int64(18)

In [76]:
v.dot(u)

np.int64(18)

In [87]:
# Matrix-Vector multiplication

U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [91]:
v = np.array([1, 0.5, 2, 1])

In [101]:
def matrix_vactor_multiply(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    temp = np.zeros(num_rows)
    
    for i in range(num_rows):
        temp[i] = vector_vector_multiplication(U[i], v)
        
    return temp

In [102]:
matrix_vactor_multiply(U, v)

array([20. ,  6. ,  8.5])

In [90]:
U.dot(v)

array([14,  5,  5])

In [94]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [96]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [97]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [98]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [99]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
X = [
    [148, 24, 135],
    [118, 14, 235],
    [235, 20, 321],
    [345, 23, 432],
    [231, 15, 323],
    [342, 18, 432],
    [123, 24, 112],
    [431, 25, 100],
    [184, 26, 235],
    [199, 19, 119],
]

X = np.array(X)
X

array([[148,  24, 135],
       [118,  14, 235],
       [235,  20, 321],
       [345,  23, 432],
       [231,  15, 323],
       [342,  18, 432],
       [123,  24, 112],
       [431,  25, 100],
       [184,  26, 235],
       [199,  19, 119]])

In [22]:
ones = np.ones(X.shape[0])
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
X = np.column_stack([ones, X])
X

array([[  1., 148.,  24., 135.],
       [  1., 118.,  14., 235.],
       [  1., 235.,  20., 321.],
       [  1., 345.,  23., 432.],
       [  1., 231.,  15., 323.],
       [  1., 342.,  18., 432.],
       [  1., 123.,  24., 112.],
       [  1., 431.,  25., 100.],
       [  1., 184.,  26., 235.],
       [  1., 199.,  19., 119.]])

In [25]:
y = [180000, 202000, 250000, 260000, 210000, 230000, 150000, 300000, 200000, 219000]

In [26]:
XTX = X.T.dot(X)

In [27]:
XTX_inv = np.linalg.inv(XTX)

In [28]:
XTX.dot(XTX_inv).round(1)

array([[ 1.,  0.,  0.,  0.],
       [-0.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -0.],
       [-0.,  0., -0.,  1.]])

In [29]:
w_full = XTX_inv.dot(X.T).dot(y)

w_full

array([ 1.72048805e+05,  3.86652483e+02, -1.60906176e+03, -3.91802197e+01])

In [31]:
w0 = w_full[0]
w = w_full[1:]

In [32]:
w0, w

(np.float64(172048.80526006242),
 array([  386.65248302, -1609.0617577 ,   -39.18021972]))

In [33]:
# define a function

In [34]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)

    return w_full[0], w_full[1:]

In [39]:
train_linear_regression(X, y)

(np.float64(172048.80526006242),
 array([  386.65248302, -1609.0617577 ,   -39.18021972]))

In [ ]:
# Root Mean Squared Error (RMSE)

In [41]:
def rmse(y, y_pred):
    error = y - y_pred
    se = error ** 2
    mse = se.mean()
    return np.sqrt(mse)

In [42]:
def rmse(y, y_pred):
    se = (y - y_pred) ** 2
    mse = se.mean()
    return np.sqrt(mse)

In [47]:
rmse(y_train, y_pred)

NameError: name 'y_train' is not defined